### ISSUE TITLE
Not an issue really but what does Has Max Targets and Max targets actually do?

### ISSUE THREAD

**Issue by Kablumbaa** [TheUnknownCod3r/Scopophobia#1]
Does it mean he will chase and kill up to 32 people (by default in config) untill he calms down?

**Comment by AuroraDoesCode** [comment]
> Does it mean he will chase and kill up to 32 people (by default in config) untill he calms down?

I believe it’s the count of players in the lobby, by default max of 32 with more company, in game only those who trigger shy guy by looking at him, and starting the animation will die.

**Comment by Kablumbaa** [comment]
Ahh got it, Thanks a lot for the quick answer!
