### ISSUE TITLE
Suggestion for the mod

### ISSUE THREAD

**Issue by ko0416** [TheUnknownCod3r/Scopophobia#2]
Hello,

Thank you for creating this mod. I personally have a suggestion. How about giving the option that it stops killing when there is certain number of players alive?

**Comment by AuroraDoesCode** [comment]
> Hello,
> 
> Thank you for creating this mod. I personally have a suggestion. How about giving the option that it stops killing when there is certain number of players alive?

Not really sure thats a viable possibility, the way the mod works is its a player based trigger, where looking at the shy guy for too long triggers the hunt and kill. I suppose you could add a config that has min players required to chase, and add it to the stare trigger as an if statement.

**Comment by AuroraDoesCode** [comment]
> > Hello,
> > Thank you for creating this mod. I personally have a suggestion. How about giving the option that it stops killing when there is certain number of players alive?
> 
> Not really sure thats a viable possibility, the way the mod works is its a player based trigger, where looking at the shy guy for too long triggers the hunt and kill. I suppose you could add a config that has min players required to chase, and add it to the stare trigger as an if statement.

Closing, as having Shy guy in a solo game with this config turned on would defeat the purpose. May as well just remove the mod at that point.
