### ISSUE TITLE
[Question] Game version compatibility

### ISSUE THREAD

**Issue by DatBoi302** [TheUnknownCod3r/Scopophobia#3]
Is it safe to update this mod to the latest version (1.1.3) which is meant in support of game v.55, while still running on game v.50? Or will I have to use mod v.1.1.2 which is meant for game v.50 specifically?

Context:
Playing with a large group, some already updated the mod, some are having trouble downloading my mod load order, some are having trouble rolling back the mod version, blah blah blah, just the normal large group stuff. Just wondering if the latest version works that way everyone can just update their mod and be done.

**Comment by AuroraDoesCode** [comment]
Correction, 1.1.3 is v55 only, 1.1.2 is for v50.

In terms of game versioning, the latest version should work fine regardless of versions. If not, please let me know.

**Comment by AuroraDoesCode** [comment]
Closed as latest live version is now v55 by default. You can revert to the old branch via steam, and just use v1.1.2
