### ISSUE TITLE
Shy guy doesn't kill

### ISSUE THREAD

**Issue by RobertLeSanglier** [TheUnknownCod3r/Scopophobia#4]
Hello, I have been testing the shy guy a few times and he never kills the player. I have let him catch me several times and he doesn't kill me on contact. He then stands still and doesn't do anything besides screaming.

We've been playing with the latest mod version on v50 lethal company. I have noticed that it is the same issue with the Shrimp enemy mod : doesn't kill nor damage on contact.

We love the mod and would like the shy guy to be a threat. Could you please fix the issue when you've got the time or tell us what you think is wrong with our mod ?

Thank you and have a nice day !

**Comment by AuroraDoesCode** [comment]
You need to downgrade to v1.1.2, sadly Thunderstore doesn't have a way to serve specific files across versions, and the Signatures for KillPlayer changed in v55, so it will not work in any lower version.

**Comment by RobertLeSanglier** [comment]
You were right it works great in v1.1.2 ! Thank you for your help !

**Comment by AuroraDoesCode** [comment]
Marking as solved. For versions < v55, use v1.1.2 of Scopophobia, for v55 and beyond, current release is fine.
