### ISSUE TITLE
The module 1.1.4 is not working

### ISSUE THREAD

**Issue by Sky-Warlock** [TheUnknownCod3r/Scopophobia#5]
1.1.4 The shyguy I met didn't seem to track its targets

**Comment by AuroraDoesCode** [comment]
> 1.1.4 The shyguy I met didn't seem to track its targets

Fixed in v1.1.5, I appreciate the bug report. Turns out the way I did the new Elevator code was incorrect. 

Thanks again, please feel free to open a bug report for anything else you may come across :)
